# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 14:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('choice_id', models.AutoField(primary_key=True, serialize=False)),
                ('choice_answer', models.BooleanField(default=False)),
                ('choice_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionMC',
            fields=[
                ('questionMC_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('questionMC_maxMarks', models.IntegerField(default=0)),
                ('questionMC_attempted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSA',
            fields=[
                ('questionSA_id', models.AutoField(primary_key=True, serialize=False)),
                ('questionSA_text', models.TextField()),
                ('questionSA_answer', models.TextField()),
                ('questionSA_maxMarks', models.IntegerField(default=0)),
                ('questionSA_attempted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quiz_id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_name', models.CharField(max_length=35)),
                ('quiz_startDateTime', models.DateTimeField()),
                ('quiz_endDateTime', models.DateTimeField()),
                ('quiz_maxMarks', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User_QuizMarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marksScored', models.IntegerField(default=0)),
                ('quizMarks_completed', models.BooleanField()),
                ('quizMarks_rank', models.IntegerField(null=True)),
                ('quizMarks_quiz', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='quizportal_app.Quiz')),
                ('quizMarks_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_quizes', models.ManyToManyField(null=True, to='quizportal_app.Quiz')),
            ],
        ),
        migrations.AddField(
            model_name='questionmc',
            name='questionMC_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizportal_app.Quiz'),
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_questionMC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizportal_app.QuestionMC'),
        ),
    ]
