# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizportal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_quizes',
            field=models.ManyToManyField(to='quizportal_app.Quiz'),
        ),
    ]
