# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizportal_app', '0002_auto_20160719_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsa',
            name='questionSA_quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizportal_app.Quiz'),
        ),
        migrations.AlterField(
            model_name='questionmc',
            name='questionMC_quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizportal_app.Quiz'),
        ),
    ]
